# Generated by Django 3.0 on 2020-02-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=20)),
                ('is_Delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_image', models.ImageField(upload_to='goods')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_Delete', models.BooleanField(default=False)),
                ('goods_click', models.IntegerField()),
                ('goods_unit', models.CharField(default='500g', max_length=20)),
                ('goods_introduce', models.CharField(max_length=200)),
                ('goods_stock', models.IntegerField()),
                ('goods_content', models.CharField(max_length=1000)),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods_Type')),
            ],
        ),
    ]
